name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: List directory contents
      run: |
        dir
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon=NONE --name "低负毛利报表" main.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: 低负毛利报表
        path: dist/低负毛利报表.exe
